(let ([a 1]) 
    (let ([b 2])
        (let ([c (+ a 1)])
            (let ([d (+ a b)])
                (let ([e (+ c d)])
                    (let ([f (- a e)])
                         (+ a (+ b (+ c (- d (+ e f)))))
                    ))))))
                        ; (let ([g (+ c (read))])
                        ;     (- (+ a (+ b c)) (+ d (+ e (- f (let ([h (- g (read))])
                        ;                                         (let ([i (+ h (read))])
                        ;                                                 (let ([j (read)])
                        ;                                                     (let ([k (+ i j)])
                        ;                                                         (let ([l (- k)])
                        ;                                                             (let ([m (- 3 (read))])
                        ;                                                                 (+ g (- h (+ i (- j (+ k (- l m))))))))))))))))))))))))
